version: '3.8'
services:

  frontend:
    build:
      context: './frontend'
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000

  express-api:
    build:
      context: './server'
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 4000:4000
